version: '3.4'

x-healthcheck-defaults: &default-healthchecks
  interval: 30s
  timeout: 10s
  retries: 3

x-justt-volumes: &justt-volumes
  - ./:/usr/app
  - /usr/app/node_modules

services:
  api:
    container_name: "${API_HOST}"
    build:
      context: ./
      target: development
      dockerfile: ./apps/api/Dockerfile
    command: ["./scripts/wait-for-it.sh", "${DB_HOST}:${DB_PORT}", "--", "./scripts/docker-api-dev.sh", "${DATABASE_URL}"]
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      *justt-volumes
    ports:
      - "${API_PORT}:3333"
    healthcheck:
      test: ['CMD', 'curl', '-f', "http://localhost:${API_PORT}"]
      <<: *default-healthchecks

  app:
    container_name: "${APP_HOST}"
    build:
      context: ./
      target: builder
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/front-website/Dockerfile
    volumes:
      *justt-volumes
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: ["npm", "run", "serve:web"]
    healthcheck:
      test: ['CMD', 'curl', '-f', "http://localhost:${APP_PORT}"]
      <<: *default-healthchecks

  webserver:
    image: nginx:1.19.2
    container_name: justt-webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - postgres
    environment:
      # host.docker.internal is the hostname that resolves host's machine
      # localhost - specific  to OS X and Linux, needs adjustment to
      # work under Windows
      - APP_HOST=host.docker.internal
      - APP_PORT=${APP_PORT}
      - API_HOST=host.docker.internal
      - API_PORT=${API_PORT}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:14-alpine
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
